/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

import { defineNuxtPlugin } from "#app";

export default defineNuxtPlugin((nuxtApp) => {
  const routesList = {
    chips: "chips",
    index: "index",
    login: "login",
    overview: "overview",
    register: "register",
    teamCreate: "team-create",
    team: "team",
    teamJoin: "team-join",
    testComponents: "test-components",
  };

  return {
    provide: {
      typedRouter: nuxtApp.$router,
      routesList,
    },
  };
});
