/**
 * ---------------------
 * 🚗🚦 Generated by nuxt-typed-router. Do not modify !
 * ---------------------
 * */

export const routerPagesNames = {
  chips: "chips" as const,
  index: "index" as const,
  login: "login" as const,
  overview: "overview" as const,
  register: "register" as const,
  teamCreate: "team-create" as const,
  team: "team" as const,
  teamJoin: "team-join" as const,
  testComponents: "test-components" as const,
};

export type TypedRouteList =
  | "chips"
  | "index"
  | "login"
  | "overview"
  | "register"
  | "team-create"
  | "team"
  | "team-join"
  | "test-components";
